import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "../components/layout/Layout";
import AuthGuard from "@/components/AuthGuard";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                function setTheme(theme) {
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                  localStorage.setItem('theme', theme);
                }

                const query = window.matchMedia('(prefers-color-scheme: dark)');
                let theme = localStorage.getItem('theme');
                if (!theme) {
                  theme = query.matches ? 'dark' : 'light';
                }

                setTheme(theme);

                query.addEventListener('change', (e) => {
                  if (!localStorage.getItem('theme')) {
                    setTheme(e.matches ? 'dark' : 'light');
                  }
                });
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-12 sm:pb-0`}
      >
        
        <AuthGuard>
          <Layout>
            {children}
          </Layout>
        </AuthGuard>

      </body>
    </html>
  );
}